---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grpc-controller
  namespace: openfaas
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grpc-controller-rw
  namespace: openfaas
rules:
- apiGroups: ["openfaas.com"]
  resources: ["functioningresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grpc-controller-rw
  namespace: openfaas-fn
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grpc-controller-rw
  namespace: openfaas
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: grpc-controller-rw
subjects:
- kind: ServiceAccount
  name: grpc-controller
  namespace: openfaas
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grpc-controller-rw
  namespace: openfaas-fn
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: grpc-controller-rw
subjects:
- kind: ServiceAccount
  name: grpc-controller
  namespace: openfaas